# readour/kafka-compose.yml
services:
  redpanda:
    image: redpandadata/redpanda:v24.2.9
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --node-id
      - "1"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
volumes:
  redpanda_data:
